version: "3.8"

services:
  workspace:
    image: kcr.intl.krosf.com/devcontainers:php7.4-workspace-laravel
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ..:/laravel
      - ~/.ssh:/home/vscode/.ssh:ro
      - vscode:/home/vscode/.vscode-server
      - composer:/home/vscode/.composer
      - /Users/krosf/.zsh_history:/home/vscode/.zhistory

  php-fpm:
    image: kcr.intl.krosf.com/php:7.4-fpm-alpine-laravel
    volumes:
      - ..:/laravel
    depends_on:
      - workspace

  ine:
    image: kcr.intl.krosf.com/nginx:1.17-php-laravel
    depends_on:
      - php-fpm
    volumes:
      - ..:/laravel
    expose:
      - 80
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx.entrypoints: web

volumes:
  composer:
  vscode:

networks:
  default:
    external:
      name: traefik
